### ISSUE TITLE
Test in terminal keeps failing

### ISSUE THREAD

**Issue by jakin010** [VakhoKontridze/VComponents#11]
Keep getting this error after testing with the terminal

Command: ``` xcodebuild -project test.xcodeproj -scheme test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 pro,OS=17.2' test | xcbeautify ```

<img width="2542" alt="Screenshot 2024-01-30 at 4 04 38 PM" src="https://github.com/VakhoKontridze/VComponents/assets/70723946/b2bc4835-9efc-4676-939f-bff7d8efc4ee">
<img width="1706" alt="Screenshot 2024-01-30 at 4 10 11 PM" src="https://github.com/VakhoKontridze/VComponents/assets/70723946/17d6c703-13e3-49b1-9ce3-447e04a646e4">

**Comment by VakhoKontridze** [comment]
I can recreate this. All errors occur because of macros. Although, tests pass just fine within the [VCore](https://github.com/vakhokontridze/vcore) package. It's Terminal that's having issues.

This seems to be a global issue, since I found several threads online. But there isn't a clear solution yet.

https://stackoverflow.com/q/77386744/11627169
https://forums.developer.apple.com/forums/thread/737908
Or, just search for "External macro implementation type could not be found for macro"

Don't know how to proceed here. Might be worth filing a bug report to Apple, assuming that it's their issue.

**Comment by jakin010** [comment]
It's weird the error only shows if testing in the terminal with a simulator but testing with a physical device in terminal no problem

**Comment by VakhoKontridze** [comment]
I see. It might be an issue with XCode and Command Line Tools. You can report it to Apple. But they might be aware of it, and it may even get fixed in the next release.
