### ISSUE TITLE
Xcode Cloud SPM Error

### ISSUE THREAD

**Issue by mrsunx** [VakhoKontridze/VComponents#13]
Target 'VCoreMacrosImplementation' must be enabled before it can be used.

**Comment by VakhoKontridze** [comment]
Hey. `VComponents` uses Swift macros, so they have to be enabled each time a new version is checked out.

I can't comment on XCode cloud, as I don't use it. But, this issue is not tied to `VComponents` in particular. There seem to be resolutions, though. Check out the following threads.

https://stackoverflow.com/q/77267883/11627169
https://forums.developer.apple.com/forums/thread/739347

**Comment by mrsunx** [comment]
> Hey. `VComponents` uses Swift macros, so they have to be enabled each time a new version is checked out.
> 
> I can't comment on XCode cloud, as I don't use it. But, this issue is not tied to `VComponents` in particular. There seem to be resolutions, though. Check out the following threads.
> 
> https://stackoverflow.com/q/77267883/11627169 https://forums.developer.apple.com/forums/thread/739347

Thanks
