### ISSUE TITLE
Amazing components - TextView Input Field above the Keyboards?

### ISSUE THREAD

**Issue by waelsaad** [VakhoKontridze/VComponents#6]
Hi,

Thank you for this amazing implementation of the components, learning so much from it.

I am just woundering if we have a Form with a number of textfields and the last one is a TextView field is there a solution to make sure where any TextField or TextView field scrolls up to be above the keyboard whenever the user starts to ente text?

Thanks.

Wael

**Comment by VakhoKontridze** [comment]
Hi there,

Thanks for the info.

An approach that ensures that even the bottom inputs pin to the top of the keyboard is wrapping the content inside the `ScrollView`. I have played around with native `TextField`. Turns out, it's an issue with the `SwiftUI`, not my library.

Consider the following code:

```
var body: some View {
    ScrollView(content: {
        VStack(spacing: 20, content: {
            ForEach(1..<20, id: \.self, content: { i in
                TextField(
                    "",
                    text: .constant("Lorem ipsum \(i)"),
                    axis: .vertical
                )
                    .textFieldStyle(.roundedBorder)
            })
        })
            .padding()
    })
        .onTapGesture(perform: {
            _ = UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)
        })
}
```

My `VTextView` is a simple wrapper on native `TextField`. The actual issue comes from the `axis` parameter, which turns the native `TextField` from single-line to multi-line input. Comment out the line—`axis: .vertical`—and issue will go away.

I don't know if it's an intended behavior, but looks like a bug to me. Consider reporting it to Apple directly [here](https://www.apple.com/feedback).

**Comment by waelsaad** [comment]
Thank you for the response. I appreciate it.
