### ISSUE TITLE
VComponents 3.2.3 and VCore 4.11.0  not compatible

### ISSUE THREAD

**Issue by underthestar** [VakhoKontridze/VComponents#8]
When I use both versions, I get an error.
<img width="1315" alt="WechatIMG187" src="https://github.com/VakhoKontridze/VComponents/assets/32029098/d2026173-5505-4e5c-acb4-47a1f81cadfc">

**Comment by VakhoKontridze** [comment]
Thanks for the feedback. `VComponents` `3.x.x` is no longer maintained. There are couple of options of tackling this:

1. Update `VComponents` to latest version (`4.3.4`), which is compatible with the latest version of `VCore`. This update may require migration within the codebase and may not be suitable.

2. Add `VCore` as another Switch Package dependency in your project, and set its version to never reach `4.11.0`, namely `4.0.0` - <`4.11.0`. This way, compilation errors will go away.

<img width=100% src="https://github.com/VakhoKontridze/VComponents/assets/57289621/83e46f17-918f-41c4-a1e4-7af430ce239c">

<img width=50% src="https://github.com/VakhoKontridze/VComponents/assets/57289621/f5434504-f1f1-480b-96f5-12144e46af80">

3. Third option requires forking `VComponents` from it's last desired commit, and adding an explicit support for `VCore` `4.11.0`. But since `3.x.x` is no longer maintained, there's no guarantee that future problems wont exist.
